channels:
  - conda-forge
  - mantid
dependencies:
  - mantidworkbench
  - jupyter-server-proxy>=1.4
  - pip
  - websockify
  - jupytext
  - nodejs
  - mcstas
  - ncrystal
  - mcpl
  - nexus
  - openmpi
  - nbgitpuller
  - pip:
      - McStasScript
      - guide_bot
      - .
